/** This is the main module */

/** Sets aliases */
let Application = PIXI.Application,
    Sprite = PIXI.Sprite,
    Graphics = PIXI.Graphics,
    Container = PIXI.Container,
    Text = PIXI.Text,
    Texture = PIXI.Texture,
    loader = PIXI.Loader.shared.loader;

// initiate the application
let app = new Application({
    width: window.innerWidth,
    height: window.innerHeight,
    antialias: true,
    transparent: false,
    resolution: 1
});

// Fit the canvas perfectly into the screen.
app.renderer.view.style.position = "absolute";
app.renderer.view.style.display = "block";
app.renderer.autoDensity = true;

// Add the canvas generated by PIXI to the DOM.
document.body.appendChild(app.view);

setup();

/** Initiates game state by adding all default creatures */
function setup() {
    
}

function gameloop() {

}